-- MariaDB dump 10.19-11.3.2-MariaDB, for Linux (x86_64)
--
-- Host: localhost    Database: hw7
-- ------------------------------------------------------
-- Server version	11.3.2-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `products`
--

LOCK TABLES `products` WRITE;
/*!40000 ALTER TABLE `products` DISABLE KEYS */;
INSERT INTO `products` VALUES
(1,'EOSR7 18-150','$1,799.00','https://s7d1.scene7.com/is/image/canon/5137C009_eos-r7-rf-s18-150mm-f35-63-is-stm_primary?fmt=webp-alpha','With a 15 FPS mechanical shutter, the high-performance EOS R7 is the most advanced APS-C camera from Canon. Featuring a high-speed shooting 32.5 MP sensor, in-body stabilization up to 7 stops with coordinated control IS'),
(2,'EOS 5D Mark IV','$2,299.00','https://s7d1.scene7.com/is/image/canon/1483C002_eos-5d-mark-iv_1NEW?fmt=webp-alpha','The EOS 5D Mark IV camera builds on the powerful legacy of the 5D series, offering amazing refinements in image quality, performance and versatility. Canon\'s commitment to imaging excellence is the soul of the EOS 5D Mark IV. Wedding and portrait photographers, nature and landscape shooters, as well as creative videographers will appreciate the brilliance and power that the EOS 5D Mark IV delivers. Superb image quality is achieved with Canon\'s all-new 30.4 Megapixel full-frame sensor, and highly-detailed 4K video is captured with ease. Focus accuracy has been improved with a refined 61-point AF system and Canon\'s revolutionary Dual Pixel CMOS AF for quick, smooth AF for both video and Live View shooting. Fast operation is enhanced with Canon\'s DIGIC 6+ Image Processor, which provides continuous shooting at up to 7.0 fps*. Built-in Wi-Fi®**, GPS*** and an easy-to-navigate touch-panel LCD allow the camera to become an extension of you. When quality matters, the EOS 5D Mark IV helps deliver results to inspire even the most discerning imagemaker.'),
(3,'EOS-1D X Mark III','$6,499.00','https://s7d1.scene7.com/is/image/canon/3829C019_primary?fmt=webp-alpha','The ultimate EOS is here, making way for a new era in autofocus speed, accuracy and precision - the EOS-1D X Mark III. Offering the highest level of performance an EOS DSLR has ever possessed, the EOS-1D X Mark III changes the game for serious photographers around the world, boasting a powerful new 20.1 Megapixel Full-frame CMOS sensor, combined with a cutting-edge new DIGIC X image processor, for truly outstanding stills and video. Track subjects with incredible focus using the new 191-point AF system - including innovative new Head Detection AF technology (EOS iTR*'),
(4,'EOS 5D Mark IV EF 24-105mm f/4L IS II USM Lens Kit','$3,399.00','https://s7d1.scene7.com/is/image/canon/1483C010_eos-5d-mark-iv-ef-24-105mm-f-4l-is-ii-usm-lens-kit_primary?fmt=webp-alpha','The EOS 5D Mark IV camera builds on the powerful legacy of the 5D series, offering amazing refinements in image quality, performance and versatility. Canon\'s commitment to imaging excellence is the soul of the EOS 5D Mark IV. Wedding and portrait photographers, nature and landscape shooters, as well as creative videographers will appreciate the brilliance and power that the EOS 5D Mark IV delivers. Superb image quality is achieved with Canon\'s all-new 30.4 Megapixel full-frame sensor, and highly-detailed 4K video is captured with ease. Focus accuracy has been improved with a refined 61-point AF system and Canon\'s revolutionary Dual Pixel CMOS AF for quick, smooth AF for both video and Live View shooting. Fast operation is enhanced with Canon\'s DIGIC 6+ Image Processor, which provides continuous shooting at up to 7.0 fps*. Built-in Wi-Fi®**, GPS*** and an easy-to-navigate touch-panel LCD allow the camera to become an extension of you. When quality matters, the EOS 5D Mark IV helps deliver results to inspire even the most discerning imagemaker.'),
(5,'EOS 6D Mark II','$1,399.00','https://s7d1.scene7.com/is/image/canon/1897C002_eos-6d-mark-ii_primary?fmt=webp-alpha','For superb performance on the go, the Canon EOS 6D Mark II camera puts full-frame performance into a compact, fully featured DSLR. Its 26.2 Megapixel CMOS sensor and DIGIC 7 Image Processor help deliver amazing results even at expanded ISO settings, making it great for challenging low-light situations as well as landscape, portrait and event photography. The EOS 6D Mark II also features an impressive optical viewfinder with 45 all cross-type AF points*, fast and accurate Dual Pixel CMOS AF and a Vari-angle Touch Screen LCD for Live View operation which helps create unique angles. With the EOS 6D Mark II\'s speed to capture action and the versatility to create phenomenal photographs and Full HD 60p videos in numerous environments and lighting situations, the camera offers creative content makers a winning combination of advanced features in a portable package that\'s as fun as it is powerful.'),
(6,'EOS 90D EF-S 18-135mm f/3.5-5.6 IS USM Kit','$1,599.00','https://s7d1.scene7.com/is/image/canon/3616C016_eos-90d-and-ef-s-18-135mm-f-3.5-5.6-is-usm-kit_5?fmt=webp-alpha','Fast. Versatile. Impressive. Whether capturing high-speed sporting events or simple, everyday moments, the EOS 90D camera is engineered to deliver impressive results. Equipped with an enhanced 32.5 Megapixel CMOS (APS-C) sensor, powerful DIGIC 8 image processor and an ISO range of 100-25000 (expandable to 51200), you\'ll achieve sharp, detailed images, even in low-light settings. Perfect for fast-moving subjects, the EOS 90D camera features a 45-point cross-type AF system* and EOS iTR AF (face detection) - plus high-speed continuous shooting of up to 10 fps - raising the game for wildlife and motor sports photography enthusiasts. And with stunning uncropped 4K 30p video capability, the EOS 90D documents your travels, events and other milestones in full, wide-angle view. No matter where your photography ventures take you, the EOS 90D proves to be the versatile, all-around SLR camera you didn’t know you were missing. '),
(7,'EOS Rebel T7 EF-S 18–55mm f/3.5–5.6 IS II','$479.99','https://s7d1.scene7.com/is/image/canon/2727C002_eos-rebel-t7-ef-s-18-55mm-is-ii-kit_2?fmt=webp-alpha','Want to share your favorite photos on social media? That\'s no problem with the EOS Rebel T7\'s built-in Wi-Fi®* and NFC** technology, making sharing and uploading photos effortless. This camera also comes equipped with a large LCD display, fast autofocus system and Full HD video recording for a variety of impressive, easy-to-use features.'),
(8,'EOS R5 C','$3,599.00','https://s7d1.scene7.com/is/image/canon/5077C002_eos-r5-c_primary_clean?fmt=webp-alpha','The EOS R5 C is a complete package that offers filmmakers, multimedia journalists, and advanced amateurs a cost-effective 8K, 4K, and FHD video camera to help unlock their creative potential.'),
(9,'EOS 5D Mark IV','$2,299.00','https://s7d1.scene7.com/is/image/canon/1483C002_eos-5d-mark-iv_1NEW?fmt=webp-alpha','The EOS 5D Mark IV camera builds on the powerful legacy of the 5D series, offering amazing refinements in image quality, performance and versatility. Canon\'s commitment to imaging excellence is the soul of the EOS 5D Mark IV. Wedding and portrait photographers, nature and landscape shooters, as well as creative videographers will appreciate the brilliance and power that the EOS 5D Mark IV delivers. Superb image quality is achieved with Canon\'s all-new 30.4 Megapixel full-frame sensor, and highly-detailed 4K video is captured with ease. Focus accuracy has been improved with a refined 61-point AF system and Canon\'s revolutionary Dual Pixel CMOS AF for quick, smooth AF for both video and Live View shooting. Fast operation is enhanced with Canon\'s DIGIC 6+ Image Processor, which provides continuous shooting at up to 7.0 fps*. Built-in Wi-Fi®**, GPS*** and an easy-to-navigate touch-panel LCD allow the camera to become an extension of you. When quality matters, the EOS 5D Mark IV helps deliver results to inspire even the most discerning imagemaker.'),
(10,'Extender RF2x','$599.99','https://s7d1.scene7.com/is/image/canon/4114C002_extender-rf2x_primary?fmt=webp-alpha',NULL),
(11,'RF100-500mm F4.5-7.1 L IS USM','$2,699.00','https://s7d1.scene7.com/is/image/canon/4112C002_rf100-500mm-f45-71-l-is-usm_primary?fmt=webp-alpha','The RF100-500mm F4.5-7.1 L IS USM super telephoto zoom lens delivers a superb combination of cutting-edge performance, compact construction and brilliant resolving power specifically designed for the EOS R system. The versatile range of 100mm to 500mm is ideal for sports, wildlife, and even aviation photography while maintaining a compact, travel-ready size and weight. The lens features one Super UD and six UD lenses. Fluorine coated front and rear lens elements provide resistance to dirt, moisture and oils, while L-series construction with dust and weather resistance provide reliability even in challenging conditions. With its built-in, 3-mode, and up-to 5-stop optical image stabilization system, and high-speed Dual Nano USM autofocus motors, the RF100-500mm F4.5-7.1 L IS USM will prove its superb optical performance, over and over again.'),
(12,'RF600mm F11 IS STM','$799.99','https://s7d1.scene7.com/is/image/canon/3986C002_rf600mm-f11-is-stm_primary?fmt=webp-alpha','The RF600mm F11 IS STM super-telephoto lens provides a long 600 millimeter focal length and is the first compact and lightweight 600mm super telephoto lens in the RF lineup. This lens is ideal forbird, wildlife, outdoor sports, and aviation. The size of this lens, and its retracting design, make it a highly portable option which can be stored easily in a camera bagand the built-in optical image stabilization with up to 5 stops of shake correction* makes it easy to use either hand-held or with a monopod. The RF600mm F11 IS STM lens will also accept an RF 1.4X or 2.0X teleconverter'),
(13,'Refurbished EF 50mm f/1.4 USM','$229.00','https://s7d1.scene7.com/is/image/canon/EF50mm_F1.4?fmt=webp-alpha','Standard lens featuring superb quality and portability. Two high-refraction lens elements and new Gaussian optics eliminate astigmatism and suppress astigmatic difference. Crisp images with little flare are obtained even at the maximum aperture.'),
(14,'Battery Pack LP-E10','$60.00','https://s7d1.scene7.com/is/image/canon/Canon_5108B002_LP_E10_Lithium_Ion_Battery_Pack_760665?fmt=webp-alpha','Compatible with Canon LC-E10 battery charger.'),
(15,'Battery Pack BP-718','$90.00','https://s7d1.scene7.com/is/image/canon/23875_1_xl?fmt=webp-alpha','Compatibility'),
(16,'XF605','$4,299.00','https://s7d1.scene7.com/is/image/canon/5076C002_xf605_primary?fmt=webp-alpha','The camera features built-in Wi-Fi/Ethernet for Browser Remote, CTM (Content Transfer Mobile) app, IP streaming, and FTP transfer. The camera is also the first XF-series camera to feature USB Video Class allowing use as a webcam without the need for a 3rd Party HDMI to USB adapter. '),
(17,'PowerShot G7 X Mark II','$699.99','https://s7d1.scene7.com/is/image/canon/1066C001_powershot-g7-x-mark-ii_primary?fmt=webp-alpha','Illuminate Your Passion'),
(18,'PowerShot ELPH 360 HS','$329.99','https://s7d1.scene7.com/is/image/canon/1078C001_powershot-elph-360-hs-silver_primary?fmt=webp-alpha','Bold Photography Day or Night.'),
(19,'EOS R8','$1,399.00','https://s7d1.scene7.com/is/image/canon/eos_r8_body_primary?fmt=webp-alpha','The EOS R8 camera combines high-performance full-frame capabilities with a lightweight and compact design for creators ready to step up their content creation. With a 24.2 megapixel full-frame CMOS image sensor, RF mount allowing access to various creative lenses, and powerful stills and video functionality, the EOS R8 camera helps you capture stunning imagery to empower your creative vision.'),
(20,'EOS R5 C RF24–105mm F4 L IS USM Lens Kit','$4,699.00','https://s7d1.scene7.com/is/image/canon/5077C010_eos-r5-c--rf24–105mm-f4-l-is-usm-lens-kit_primary?fmt=webp-alpha','The EOS R5 C is a complete package that offers filmmakers, multimedia journalists, and advanced amateurs a cost-effective 8K, 4K, and FHD video camera to help unlock their creative potential.'),
(21,'Nikon D780 Digital SLR Camera Body','$1,996.95','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNjU1ODB4MjAwMC5qcGc=_H_SW100_MH100.jpg',' Incredible time-lapse photography can be created with the D780 using the traditional interval timer, in-camera time-lapse feature, or a new mode that creates a time-lapse image in-camera from photos captured with the interval timer, offering the best of both worlds.'),
(22,'Nikon D850 Digital SLR Camera Body','$2,496.95','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNTM2Mzl4MTUwMF9GRy5qcGc=_H_SW100_MH100.jpg',' Incredible time-lapse photography can be created with the D780 using the traditional interval timer, in-camera time-lapse feature, or a new mode that creates a time-lapse image in-camera from photos captured with the interval timer, offering the best of both worlds.'),
(23,'Nikon D6 Digital SLR Camera Body','$6,496.95','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNjQxNDl4MTAwMC5qcGc=_H_SW100_MH100.jpg',NULL),
(24,'Nikon Z 8 Mirrorless Digital Camera Body','$3,696.95','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNzc4MDh4MTMwMF9GRzQuanBn_H_SW100_MH100.jpg',NULL),
(25,'Nikon Z 6II Mirrorless Digital Camera Body','$1,596.95','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNjc3NTh4MTAwMF9GRzMuanBn_H_SW100_MH100.jpg','Breakthroughs of the Z Mount, the largest full frame lens mount of any system, have given way to some of the most advanced, optically pristine lenses ever—NIKKOR Z. The Z 6II is compatible with them all, each one delivering a new perspective and drawing peak performance from the camera.'),
(26,'Nikon Z 6II Mirrorless Digital Camera Body with FTZ II Mount Adapter','$1,793.90','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vSy0wNjc3NThLSVRCeDExMDBfRkcxLmpwZw==_H_SW100_MH100.jpg','Breakthroughs of the Z Mount, the largest full frame lens mount of any system, have given way to some of the most advanced, optically pristine lenses ever—NIKKOR Z. The Z 6II is compatible with them all, each one delivering a new perspective and drawing peak performance from the camera.'),
(27,'Nikon D7500 Digital SLR Camera Body','$896.95','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNTE1MTd4MTUwMC5qcGc=_H_SW100_MH100.jpg','Breakthroughs of the Z Mount, the largest full frame lens mount of any system, have given way to some of the most advanced, optically pristine lenses ever—NIKKOR Z. The Z 6II is compatible with them all, each one delivering a new perspective and drawing peak performance from the camera.'),
(28,'Sony Alpha a7R V Mirrorless Digital Camera Body','$3,898.00','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNzYwODV4MTAwMF9GRzUuanBn_H_SW100_MH100.jpg','\n'),
(29,'Fujifilm X-H2 Mirrorless Digital Camera with XF 16-80mm Lens','$2,499.00','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNzU2MjZ4MTAwMF9GRzIuanBn_H_SW100_MH100.jpg','\n'),
(30,'Fujifilm XF 23mm f/2 R WR Lens (Black)','$449.00','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNDc2NzN4MTUwMC5qcGc=_H_SW100_MH100.jpg','\n'),
(31,'Nikon NIKKOR Z 24-70mm f/2.8 S Lens','$2,396.95','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNjA5NTh4MTUwMF9GRy5qcGc=_H_SW100_MH100.jpg','\n'),
(32,'Tamron 28-75mm f/2.8 Di III VXD G2 Lens for Nikon Z','$999.00','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wODEzOTZ4MTAwMC5qcGc=_H_SW100_MH100.jpg','\n'),
(33,'Canon RF 16mm f/2.8 STM Lens','$299.00','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNzEzOTN4MTAwMC5qcGVn_H_SW100_MH100.jpg','\n'),
(34,'Canon LP-E6NH Rechargeable Lithium-ion Battery','$79.99','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNjcwMDB4MjAwMC5qcGc=_H_SH480_MW480.jpg','\n'),
(35,'Sony NP-FZ100 Rechargeable Lithium-Ion Battery','$78.00','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNTE2MTR4MTUwMC5qcGc=_H_SH480_MW480.jpg','\n'),
(36,'Leica M6 Rangefinder Camera (Black)','$5,695.00','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNzU5ODN4MTAwMC5qcGc=_H_SW100_MH100.jpg','\n'),
(37,'Ricoh GR III Digital Camera','$966.95','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNjEyMDB4MTAwMC5qcGVn_H_SW100_MH100.jpg','\n'),
(38,'Sony ZV-1F Vlogging Camera (Black)','$498.00','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNzU5ODR4MTAwMF9GRy5qcGc=_H_SW100_MH100.jpg',' is a pocket-sized camera with a large 1-inch sensor and wide angle 20mm F2.0 lens, ideal for capturing more in the scene - even at arm\'s length, and excellent in low-light situations. It\'s packed with easy-to-use features, including Sony\'s acclaimed Eye-AF and autofocus tracking with simplified Background Defocus function, Face Priority AE (auto exposure) and Product Showcase setting, plus a new touchscreen interface, making it easier to use.'),
(39,'Ricoh GR III HDF Digital Camera','$1,066.95','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wODE0ODF4MTAwMC5qcGVn_H_SW100_MH100.jpg',NULL),
(40,'Sony Cyber-shot DSC-RX1R II Digital Camera','$3,298.00','https://www.samys.com/imagesproc/L2ltYWdlcy9wcm9kdWN0L21haW4vUy0wNDIwNzR4MTUwMF9GRy5qcGc=_H_SW100_MH100.jpg',NULL);
/*!40000 ALTER TABLE `products` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `transactions`
--

LOCK TABLES `transactions` WRITE;
/*!40000 ALTER TABLE `transactions` DISABLE KEYS */;
INSERT INTO `transactions` VALUES
(1,'John Doe','123 Street Boulevard','2196.65','Nikon D780 Digital SLR Camera Body','123321123321'),
(2,'Jane Doe','321 Boulevard Street','3958.9','EOS R5 C','456654456'),
(3,'Rick John','8 Road Street','1978.9','EOSR7 18-150','123456789'),
(4,'Nick John','10 Boulevard Street','2196.65','Nikon D780 Digital SLR Camera Body','11111111');
/*!40000 ALTER TABLE `transactions` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2024-04-26 19:57:00
